//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERM.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pdf")]
        public string SPDFPath {
            get {
                return ((string)(this["SPDFPath"]));
            }
            set {
                this["SPDFPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODoc")]
        public string ODOCPath {
            get {
                return ((string)(this["ODOCPath"]));
            }
            set {
                this["ODOCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MPdf")]
        public string MPDFPath {
            get {
                return ((string)(this["MPDFPath"]));
            }
            set {
                this["MPDFPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Template")]
        public string CellPath {
            get {
                return ((string)(this["CellPath"]));
            }
            set {
                this["CellPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project")]
        public string ProjectPath {
            get {
                return ((string)(this["ProjectPath"]));
            }
            set {
                this["ProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDFTemp")]
        public string PDFTemp {
            get {
                return ((string)(this["PDFTemp"]));
            }
            set {
                this["PDFTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descriptive")]
        public string descriptive {
            get {
                return ((string)(this["descriptive"]));
            }
            set {
                this["descriptive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("档案馆代号")]
        public string DagDh {
            get {
                return ((string)(this["DagDh"]));
            }
            set {
                this["DagDh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BackupData")]
        public string BackupData {
            get {
                return ((string)(this["BackupData"]));
            }
            set {
                this["BackupData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100")]
        public string tuzhang {
            get {
                return ((string)(this["tuzhang"]));
            }
            set {
                this["tuzhang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("单页签章")]
        public string SignatureModel {
            get {
                return ((string)(this["SignatureModel"]));
            }
            set {
                this["SignatureModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237")]
        public string SignatureModelPositionX {
            get {
                return ((string)(this["SignatureModelPositionX"]));
            }
            set {
                this["SignatureModelPositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("357")]
        public string SignatureModelPositionY {
            get {
                return ((string)(this["SignatureModelPositionY"]));
            }
            set {
                this["SignatureModelPositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SipIncludeDoc {
            get {
                return ((string)(this["SipIncludeDoc"]));
            }
            set {
                this["SipIncludeDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string IsFont {
            get {
                return ((string)(this["IsFont"]));
            }
            set {
                this["IsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPG,GIF,BMP,XML,DOC,XLS,PPT,TIF,PDF,DWG,CLL|*.JPG;*.GIF;*.BMP;*.XML;*.DOC;*.XLS;*" +
            ".PPT;*.TIF;*.PDF;*.DWG;*.CLL|JPG|*.JPG|GIF|*.GIF|BMP|*.BMP|XML|*.XML|DOC|*.DOC|X" +
            "LS|*.XLS|PPT|*.PPT|TIF|*.TIF|PDF|*.PDF|DWG|*.DWG|CLL|*.CLL")]
        public string FilterType {
            get {
                return ((string)(this["FilterType"]));
            }
            set {
                this["FilterType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public string TreeWidth {
            get {
                return ((string)(this["TreeWidth"]));
            }
            set {
                this["TreeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPG;XML;DOC;TIF;GIF;BMP;XLS;PPT;PDF;CLL;DWG;")]
        public string PrintType {
            get {
                return ((string)(this["PrintType"]));
            }
            set {
                this["PrintType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string PrintYjml {
            get {
                return ((string)(this["PrintYjml"]));
            }
            set {
                this["PrintYjml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("格力房产有限公司")]
        public string CellPrinterFoot {
            get {
                return ((string)(this["CellPrinterFoot"]));
            }
            set {
                this["CellPrinterFoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string IsPageNo {
            get {
                return ((string)(this["IsPageNo"]));
            }
            set {
                this["IsPageNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string PageNoLocationX {
            get {
                return ((string)(this["PageNoLocationX"]));
            }
            set {
                this["PageNoLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string PageNoLocationY {
            get {
                return ((string)(this["PageNoLocationY"]));
            }
            set {
                this["PageNoLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string PageNoLocationSize {
            get {
                return ((string)(this["PageNoLocationSize"]));
            }
            set {
                this["PageNoLocationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string IsSignature {
            get {
                return ((string)(this["IsSignature"]));
            }
            set {
                this["IsSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CJDAG")]
        public string TreeSelect {
            get {
                return ((string)(this["TreeSelect"]));
            }
            set {
                this["TreeSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Module1 {
            get {
                return ((string)(this["Module1"]));
            }
            set {
                this["Module1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Module2 {
            get {
                return ((string)(this["Module2"]));
            }
            set {
                this["Module2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工程编号(备案号)")]
        public string lbl_ProjectNO {
            get {
                return ((string)(this["lbl_ProjectNO"]));
            }
            set {
                this["lbl_ProjectNO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工程用地批准书号")]
        public string lbl_wh1 {
            get {
                return ((string)(this["lbl_wh1"]));
            }
            set {
                this["lbl_wh1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("用地规划许可证号")]
        public string lbl_wh2 {
            get {
                return ((string)(this["lbl_wh2"]));
            }
            set {
                this["lbl_wh2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工程规划许可证号")]
        public string lbl_wh3 {
            get {
                return ((string)(this["lbl_wh3"]));
            }
            set {
                this["lbl_wh3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工程施工许可证号")]
        public string lbl_wh4 {
            get {
                return ((string)(this["lbl_wh4"]));
            }
            set {
                this["lbl_wh4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Module3 {
            get {
                return ((string)(this["Module3"]));
            }
            set {
                this["Module3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Module4 {
            get {
                return ((string)(this["Module4"]));
            }
            set {
                this["Module4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string ProjectNameBind {
            get {
                return ((string)(this["ProjectNameBind"]));
            }
            set {
                this["ProjectNameBind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Project_Add {
            get {
                return ((string)(this["Project_Add"]));
            }
            set {
                this["Project_Add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Project_Modefy {
            get {
                return ((string)(this["Project_Modefy"]));
            }
            set {
                this["Project_Modefy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28E6AC73-C17E-4568-AC9F-27FF92BBD43F")]
        public string Project_Del {
            get {
                return ((string)(this["Project_Del"]));
            }
            set {
                this["Project_Del"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d")]
        public string fd {
            get {
                return ((string)(this["fd"]));
            }
            set {
                this["fd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("联系电话：0755-83995038")]
        public string lbl_t2 {
            get {
                return ((string)(this["lbl_t2"]));
            }
            set {
                this["lbl_t2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("深圳市世纪伟图科技开发有限公司")]
        public string lbl_t1 {
            get {
                return ((string)(this["lbl_t1"]));
            }
            set {
                this["lbl_t1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QQ：2689428488")]
        public string lbl_t3 {
            get {
                return ((string)(this["lbl_t3"]));
            }
            set {
                this["lbl_t3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("联系电话：0755-83995038")]
        public string lbl_phone {
            get {
                return ((string)(this["lbl_phone"]));
            }
            set {
                this["lbl_phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QQ：2689428488")]
        public string lbl_QQ {
            get {
                return ((string)(this["lbl_QQ"]));
            }
            set {
                this["lbl_QQ"] = value;
            }
        }
    }
}
